# Generated by Django 5.2.17 on 2026-10-06 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_invitation_teams'),
        ('payments', '0002_invoice_reference_invoice_reminded_at_invoice_sms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='receipt_token',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='invoice',
            name='split_code',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name='OrgPaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_code', models.CharField(blank=True, max_length=60)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pay_settings', to='orgs.organization')),
            ],
        ),
    ]
