# Generated by Django 5.2.17 on 2026-10-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=10),
        ),
    ]
