# Generated by Django 5.2.17 on 2026-10-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_backfill_finished_at'),
        ('orgs', '0002_organization_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='assigned_staff', to='competitions.team'),
        ),
        migrations.AddField(
            model_name='organization',
            name='brand_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('league', 'League'), ('school', 'School'), ('club', 'Club'), ('academy', 'Academy'), ('company', 'Company'), ('community', 'Community'), ('association', 'Association'), ('other', 'Other')], default='league', max_length=15),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_data',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('organizer', 'Competition Manager'), ('team_manager', 'Team Manager'), ('coach', 'Coach'), ('scorekeeper', 'Scorekeeper'), ('editor', 'Editor'), ('moderator', 'Moderator'), ('player', 'Player'), ('viewer', 'Viewer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('organizer', 'Competition Manager'), ('team_manager', 'Team Manager'), ('coach', 'Coach'), ('scorekeeper', 'Scorekeeper'), ('editor', 'Editor'), ('moderator', 'Moderator'), ('player', 'Player'), ('viewer', 'Viewer')], max_length=20),
        ),
    ]
