# Generated by Django 5.2.17 on 2026-10-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_backfill_finished_at'),
        ('orgs', '0003_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='invitations', to='competitions.team'),
        ),
    ]
