# Generated by Django 5.2.17 on 2026-10-06 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_invitation_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60)),
                ('title', models.CharField(max_length=80)),
                ('body', models.TextField(blank=True, max_length=20000)),
                ('published', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='orgs.organization')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('org', 'slug'), name='one_page_slug_per_org')],
            },
        ),
    ]
