# Generated by Django 5.2.17 on 2026-10-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_org_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='in_rankings',
            field=models.BooleanField(default=True),
        ),
    ]
