# Generated by Django 5.2.17 on 2026-10-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_org_in_rankings'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='open_to_friendlies',
            field=models.BooleanField(default=False),
        ),
    ]
