# Generated by Django 5.2.17 on 2026-10-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_league_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='device',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='audit',
            name='new',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='old',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='resource',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='audit',
            name='status',
            field=models.CharField(default='ok', max_length=10),
        ),
    ]
