# Generated by Django 5.2.17 on 2026-10-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_site_owner_is_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
