# Generated by Django 5.2.17 on 2026-10-07 16:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0007_competition_money'),
        ('orgs', '0006_org_in_rankings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(db_index=True, default='draft', max_length=10)),
                ('divisions', models.JSONField(default=list)),
                ('size', models.PositiveSmallIntegerField(default=6)),
                ('move', models.PositiveSmallIntegerField(default=1)),
                ('legs', models.PositiveSmallIntegerField(default=2)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_seasons', to='orgs.organization')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='SeasonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField(default=1500)),
                ('reason', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(db_index=True, default='proposed', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('checkout_url', models.URLField(blank=True, max_length=500)),
                ('division', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('final_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='competitions.competition')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='proleague.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_seasons', to='competitions.team')),
            ],
            options={
                'ordering': ['seed'],
                'constraints': [models.UniqueConstraint(fields=('season', 'team'), name='one_place_per_team_per_season')],
            },
        ),
    ]
