# Generated by Django 5.2.17 on 2026-10-05 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, choices=[('', '—'), ('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField(blank=True, editable=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=30)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('region', models.CharField(blank=True, max_length=60)),
                ('season', models.CharField(blank=True, max_length=30)),
                ('kind', models.CharField(choices=[('league', 'League'), ('tournament', 'Tournament'), ('cup', 'Cup'), ('championship', 'Championship'), ('friendly', 'Friendly series'), ('other', 'Other')], default='league', max_length=15)),
                ('format', models.CharField(choices=[('league', 'League: everyone plays everyone'), ('groups_knockout', 'Groups, then knockouts'), ('knockout', 'Knockout only')], default='league', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public: listed and shareable'), ('unlisted', 'Unlisted: only people with the link'), ('private', 'Private: members only')], default='public', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'In progress'), ('completed', 'Completed')], default='draft', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rules', models.TextField(blank=True, max_length=10000)),
                ('points_win', models.PositiveSmallIntegerField(default=3)),
                ('points_draw', models.PositiveSmallIntegerField(default=1)),
                ('points_loss', models.PositiveSmallIntegerField(default=0)),
                ('tiebreakers', models.JSONField(blank=True, default=list)),
                ('legs', models.PositiveSmallIntegerField(default=1)),
                ('max_teams', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('qualifiers_per_group', models.PositiveSmallIntegerField(default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='orgs.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField(blank=True, max_length=5000)),
                ('published', models.BooleanField(default=True)),
                ('pinned', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='orgs.organization')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='competitions.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=10)),
                ('points_adjustment', models.SmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(default='league', max_length=10)),
                ('group', models.CharField(blank=True, max_length=10)),
                ('round', models.PositiveSmallIntegerField(default=1)),
                ('round_name', models.CharField(blank=True, max_length=40)),
                ('leg', models.PositiveSmallIntegerField(default=1)),
                ('kickoff', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('referee', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_pens', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_pens', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('away', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='competitions.entry')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.competition')),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='competitions.entry')),
            ],
            options={
                'ordering': ['round', 'kickoff', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('goal', 'Goal'), ('penalty_goal', 'Penalty goal'), ('own_goal', 'Own goal'), ('yellow', 'Yellow card'), ('second_yellow', 'Second yellow'), ('red', 'Red card'), ('substitution', 'Substitution')], max_length=15)),
                ('side', models.CharField(max_length=4)),
                ('player_name', models.CharField(blank=True, max_length=80)),
                ('assist_name', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='competitions.match')),
                ('assist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='competitions.player')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='competitions.player')),
            ],
            options={
                'ordering': ['minute', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField(blank=True, editable=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=30)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=80)),
                ('short_name', models.CharField(blank=True, max_length=12)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('founded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('colors', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='orgs.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='competitions.team'),
        ),
        migrations.AddField(
            model_name='entry',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entries', to='competitions.team'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('competition', 'team'), name='team_once_per_competition'),
        ),
    ]
