# Generated by Django 5.2.17 on 2026-10-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
