# Generated by Django 5.2.17 on 2026-10-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_discovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
