# Generated by Django 5.2.17 on 2026-10-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_backfill_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
