# Generated by Django 5.2.17 on 2026-10-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_competition_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_from',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='match',
            name='home_from',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='match',
            name='slot',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
