# Generated by Django 5.2.17 on 2026-10-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_knockout_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='money',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
