# Generated by Django 5.2.17 on 2026-10-07 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_competition_money'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='decided',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='home_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MatchProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=4)),
                ('kind', models.CharField(max_length=10)),
                ('image', models.BinaryField()),
                ('content_type', models.CharField(max_length=30)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='competitions.match')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created', 'id'],
            },
        ),
    ]
