# Generated by Django 5.2.17 on 2026-10-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_match_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='third_min_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
