# Generated by Django 5.2.17 on 2026-10-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_third_min_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='best_thirds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
