# Generated by Django 5.2.17 on 2026-10-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_best_thirds'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='best_thirds_auto',
            field=models.BooleanField(default=False),
        ),
    ]
