# Generated by Django 5.2.17 on 2026-10-10 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_best_thirds_auto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendlyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff', models.DateTimeField()),
                ('message', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answered', models.DateTimeField(blank=True, null=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_sent', to='competitions.team')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='competitions.match')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_received', to='competitions.team')),
            ],
        ),
    ]
