# Generated by Django 5.2.17 on 2026-10-10 17:22

import django.db.models.deletion
from django.db import migrations, models


def fill_to_org(apps, schema_editor):
    """Existing challenges: the organization is the challenged team's."""
    FriendlyChallenge = apps.get_model("competitions", "FriendlyChallenge")
    for ch in FriendlyChallenge.objects.filter(to_org__isnull=True, to_team__isnull=False).select_related("to_team"):
        ch.to_org_id = ch.to_team.org_id
        ch.save(update_fields=["to_org"])


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_friendly_challenge'),
        ('orgs', '0007_open_to_friendlies'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlychallenge',
            name='to_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendly_challenges', to='orgs.organization'),
        ),
        migrations.AlterField(
            model_name='friendlychallenge',
            name='to_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges_received', to='competitions.team'),
        ),
        migrations.RunPython(fill_to_org, migrations.RunPython.noop),
    ]
